# Generated by Django 3.0.6 on 2020-06-15 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogreq',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('status', models.BooleanField(default=False)),
                ('date_rec', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
