# Generated by Django 3.0.6 on 2020-06-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('status', models.BooleanField(default=False)),
                ('date_rec', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
