# Generated by Django 3.0.6 on 2020-06-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogreq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreq',
            name='id',
        ),
        migrations.AddField(
            model_name='blogreq',
            name='blog_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
