# Generated by Django 3.0.6 on 2020-06-13 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogreq', '0003_auto_20200613_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreq',
            name='id',
        ),
        migrations.AddField(
            model_name='blogreq',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
