# Generated by Django 3.0.6 on 2020-06-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogreq', '0005_auto_20200613_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreq',
            name='date_rec',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
