# Generated by Django 3.0.6 on 2020-06-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='phone',
            field=models.CharField(default=9411486543, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='email',
            field=models.CharField(max_length=80),
        ),
    ]
