# Generated by Django 3.0.6 on 2020-06-13 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200613_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
